# Generated by Django 4.1.7 on 2023-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nacionalidade',
            field=models.URLField(blank=True, null=True),
        ),
    ]
